export default {
    mutations: {
        SET_USERS: 'SET_USERS',
        SET_TOTAL_USERS: 'SET_TOTAL_USERS',
        SET_USER_ROUTES: 'SET_USER_ROUTES',
        SET_ACTIVITIES_USER_ROUTES: 'SET_ACTIVITIES_USER_ROUTES',
        SET_ACTIVITIES_USER_SUBROUTES: 'SET_ACTIVITIES_USER_SUBROUTES'
    },
    getters: {
        GET_ALL_USERS: 'GET_ALL_USERS',
        GET_TOTAL_USERS: 'GET_TOTAL_USERS',
        GET_USER_ROUTES: 'FETCH_USER_ROUTES',
        GET_ACTIVITIES_USER_ROUTES: 'GET_ACTIVITIES_USER_ROUTES',
        GET_ACTIVITIES_USER_SUBROUTES: 'GET_ACTIVITIES_USER_SUBROUTES'
    },
    actions: {
        FETCH_ALL_USERS: 'FETCH_ALL_USERS',
        UPDATE_USER: 'UPDATE_USER',
        FETCH_USER_ROUTES: 'FETCH_USER_ROUTES',
        FETCH_ACTIVITIES_USER_ROUTES: 'FETCH_ACTIVITIES_USER_ROUTES',
        FETCH_ACTIVITIES_USER_SUBROUTES: 'FETCH_ACTIVITIES_USER_SUBROUTES'
    },
};
